import { NextRequest, NextResponse } from "next/server";

import {
  createMember,
  getMembers,
  searchMembers,
} from "@/lib/members/service";

/* =========================================================
   GET /api/members
========================================================= */

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;

    const search =
      searchParams.get("search")?.trim() || "";

    /*
     * Loan-specific member filtering.
     *
     * IMPORTANT:
     * This is opt-in.
     *
     * /api/members
     *      -> returns normal member results
     *
     * /api/members?forLoan=true
     *      -> returns only members eligible for a new loan
     *
     * This prevents other member routes from
     * accidentally hiding members who already have loans.
     */
    const forLoan =
      searchParams.get("forLoan") === "true";

    const pageParam =
      searchParams.get("page");

    const limitParam =
      searchParams.get("limit");

    const page =
      pageParam
        ? Number(pageParam)
        : 1;

    const limit =
      limitParam
        ? Number(limitParam)
        : 2500;

    if (
      !Number.isInteger(page) ||
      page < 1
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Page must be a positive integer.",
        },
        {
          status: 400,
        }
      );
    }

    if (
      !Number.isInteger(limit) ||
      limit < 1 ||
      limit > 100
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Limit must be an integer between 1 and 100.",
        },
        {
          status: 400,
        }
      );
    }

    const result = search
      ? await searchMembers(search, {
          page,
          limit,
          forLoan,
        })
      : await getMembers({
          page,
          limit,
          forLoan,
        });

    return NextResponse.json(
      {
        success: true,
        data: result.members,
        count: result.members.length,
        total: result.total,
        page: result.page,
        limit: result.limit,
        totalPages: result.totalPages,
      },
      {
        status: 200,
      }
    );
  } catch (error) {
    console.error(
      "GET /api/members error:",
      error
    );

    return NextResponse.json(
      {
        success: false,
        error:
          "Failed to retrieve members.",
      },
      {
        status: 500,
      }
    );
  }
}

/* =========================================================
   POST /api/members

   Member ID is generated by the server.

   The client must NOT provide:
   - memberId
   - memberID
   - member_id

   createMember() is responsible for generating
   the GEO-XXX ID and creating the member's
   savings account.
========================================================= */

export async function POST(
  request: NextRequest
) {
  try {
    let body: unknown;

    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        {
          success: false,
          error:
            "Invalid JSON request body.",
        },
        {
          status: 400,
        }
      );
    }

    if (
      !body ||
      typeof body !== "object" ||
      Array.isArray(body)
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Invalid member data.",
        },
        {
          status: 400,
        }
      );
    }

    const memberData = {
      ...(body as Record<string, unknown>),
    };

    /*
     * Member ID is server controlled.
     *
     * Never allow the browser to decide
     * which GEO number a member receives.
     */

    delete memberData.memberId;
    delete memberData.memberID;
    delete memberData.member_id;

    const member = await createMember(
      memberData
    );

    return NextResponse.json(
      {
        success: true,
        data: member,
        message:
          "Member and savings account created successfully.",
      },
      {
        status: 201,
      }
    );
  } catch (error) {
    console.error(
      "POST /api/members error:",
      error
    );

    const message =
      error instanceof Error
        ? error.message
        : "Failed to create member.";

    const knownError =
      message.includes("already exists") ||
      message.includes("already uses") ||
      message.includes("required") ||
      message.includes("Invalid") ||
      message.includes("duplicate") ||
      message.includes("phone") ||
      message.includes("member");

    return NextResponse.json(
      {
        success: false,
        error: message,
      },
      {
        status: knownError ? 400 : 500,
      }
    );
  }
}